export const supplementary = [
	{ dbName: 'github', displayName: 'Github', type: 'Code' },
	{ dbName: 'gitlab', displayName: 'Gitlab', type: 'Code' },
	{ dbName: 'codeOcean', displayName: 'Code Ocean', type: 'Container' },
	{ dbName: 'colab', displayName: 'Code Ocean', type: 'Container' },
	{ dbName: 'geo', displayName: 'Gene Expression Omnibus (Geo)', type: 'Data' },
	{ dbName: 'dbGap', displayName: 'Database of Genotypes and Phenotypes (dbGap)', type: 'Data' },
	{ dbName: 'kaggle', displayName: 'Kaggle', type: 'Data' },
	{ dbName: 'dryad', displayName: 'Dryad', type: 'Data' },
	{ dbName: 'empiar', displayName: 'Empiar', type: 'Data' },
	{ dbName: 'gigaDb', displayName: 'GigaScience Database (gigaDb)', type: 'Data' },
	{ dbName: 'zenodo', displayName: 'Zenodo', type: 'Data' }, 
	{ dbName: 'ega', displayName: 'European Genome-phenome Archive (EGA)', type: 'Data' },
	{ dbName: 'xlsx', displayName: 'Excel Document (xlsx)', type: 'Data' },
	{ dbName: 'csv', displayName: 'Comma Separated Values File (csv)', type: 'Data' },
	{ dbName: 'proteinDataBank', displayName: 'Protein Data Bank (PDB)', type: 'Data' },
	{ dbName: 'dataverse', displayName: 'Dataverse', type: 'Data' },
	{ dbName: 'openScienceframework', displayName: 'Open Science Framework (OSF)', type: 'Data' },
	{ dbName: 'finngenGitbook', displayName: 'Finngen', type: 'Data' },
	{ dbName: 'gtexPortal', displayName: 'Genotype-Tissue Expression (GTEx)', type: 'Data' },
	{ dbName: 'ebiAcUk', displayName: 'EMBLs European Bioinformatics Institute', type: 'Data' },
	{ dbName: 'mendeley', displayName: 'Mendeley', type: 'Data' },
	{ dbName: 'gsea', displayName: 'Gene Set Enrichment Analysis (GSEA)', type: 'Results' },
	{ dbName: 'figshare', displayName: 'Figshare', type: 'Results' },
	{ dbName: 'clinicalTrial', displayName: 'Clinical Trial Gov', type: 'Clinical Trials' },
	// { dbName: 'IEEE', displayName: 'IEEE', type: 'Miscellanous' },
	// { dbName: 'pdf', displayName: 'PDF', type: 'Miscellanous' },
	// { dbName: 'docx', displayName: 'Word Document (docx)', type: 'Miscellanous' },
	// { dbName: 'zip', displayName: 'Compressed Folder (zip)', type: 'Miscellanous' },
];