import { Schema } from 'mongoose';

export const PublicationChangesSchema = new Schema({
  PMID: { type: String },
  doi: { type: String, required: true },
  date: { type: String },
  name: { type: String },
  journal: { type: String },
  type: { type: String },
  authors: { type: String },
  filteredAuthors: { type: String },
  affiliations: { type: String },
  citations: { type: Number },
  dateAdded: { type: Date, default: Date.now },
  publisher: { type: String },
  status: { type: String },
  image: { type: String },
  supplementary: {
    github: { type: String },
    codeOcean: { type: String },
    geo: { type: String },
    dbGap: { type: String },
    figshare: { type: String },
    kaggle: { type: String },
    dryad: { type: String },
    empiar: { type: String },
    gigaDb: { type: String },
    dataverse: { type: String },
    IEEE: { type: String },
    mendeley: { type: String },
    openScienceframework: { type: String },
    zenodo: { type: String },
    gitlab: { type: String },
    finngenGitbook: { type: String },
    pdf: { type: String },
    docx: { type: String },
    clinicalTrial: { type: String },
    ega: { type: String },
    zip: { type: String },
    xlsx: { type: String },
    csv: { type: String },
    gtexPortal: { type: String },
    proteinDataBank: { type: String },
    ebiAcUk: { type: String },
    gsea: { type: String },
	other: { type: String },
  },
  originalId: { type: String },
  submitterEmail: {type: String}
});
