import { Schema } from "mongoose";

export const PublicationSchema = new Schema({
  PMID: Number,
  doi: String,
  date: Date,
  name: String,
  journal: String,
  type: String,
  authors: String,
  filteredAuthors: String,
  affiliations: String,
  citations: Number,
  dateAdded: Date,
  publisher: String,
  status: String,
  image: String,
  supplementary: {
    github: { type: String, default: "" },
    codeOcean: { type: String, default: "" },
    geo: { type: String, default: "" },
    dbGap: { type: String, default: "" },
    figshare: { type: String, default: "" },
    kaggle: { type: String, default: "" },
    dryad: { type: String, default: "" },
    empiar: { type: String, default: "" },
    gigaDb: { type: String, default: "" },
    dataverse: { type: String, default: "" },
    IEEE: { type: String, default: "" },
    mendeley: { type: String, default: "" },
    openScienceframework: { type: String, default: "" },
    zenodo: { type: String, default: "" },
    gitlab: { type: String, default: "" },
    finngenGitbook: { type: String, default: "" },
    pdf: { type: String, default: "" },
    docx: { type: String, default: "" },
    clinicalTrial: { type: String, default: "" },
    ega: { type: String, default: "" },
    zip: { type: String, default: "" },
    xlsx: { type: String, default: "" },
    csv: { type: String, default: "" },
    gtexPortal: { type: String, default: "" },
    proteinDataBank: { type: String, default: "" },
    ebiAcUk: { type: String, default: "" },
    gsea: { type: String, default: "" },
  },
}, { collection: 'publications' });




