import { Schema } from 'mongoose';

export const PublicationsNewSchema = new Schema({
  PMID: Number,
  doi: { type: String, required: true },
  date: String,
  name: { type: String, required: true },
  journal: String,
  type: String,
  authors: String,
  filteredAuthors: String,
  affiliations: String,
  citations: Number,
  dateAdded: String,
  publisher: String,
  status: String,
  image: String,
  supplementary: {
    github: String,
    codeOcean: String,
    geo: String,
    dbGap: String,
    figshare: String,
    kaggle: String,
    dryad: String,
    empiar: String,
    gigaDb: String,
    dataverse: String,
    IEEE: String,
    mendeley: String,
    openScienceframework: String,
    zenodo: String,
    gitlab: String,
    finngenGitbook: String,
    pdf: String,
    docx: String,
    clinicalTrial: String,
    ega: String,
    zip: String,
    xlsx: String,
    csv: String,
    gtexPortal: String,
    proteinDataBank: String,
    ebiAcUk: String,
    gsea: String,
  },
}, { collection: 'newpublications' });
